---
title: "TOP paper resources"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is a companion website to the [TOP][top-package] package and 
contains the data resources and data processing pipelines for the `TOP` paper.

  * Example [pipelines][snakemake-pipeline] using [Snakemake][snakemake] to 
  generate TOP training data used in the `TOP` paper.
  * Pretrained `TOP` [model parameters][pretrained-model].
  * Precomputed TF occupancy predictions on our lab [website][top-predictions].

**Reference**

* Luo K, Zhong J, Safi A, Hong LK, Tewari AK, Song L, Reddy TE, Ma L, 
Crawford GE, Hartemink AJ. 
Profiling the quantitative occupancy of myriad transcription factors across 
conditions by modeling chromatin accessibility data. 
Genome Res. 2022 Jun;32(6):1183-1198. doi: 10.1101/gr.272203.120.

**License**

All source code and software in this repository are made available
under the terms of the [MIT license][mit-license].

[top-package]: https://github.com/HarteminkLab/TOP
[top-webiste]: https://kevinlkx.github.io/TOP
[top-resources-github]: https://github.com/HarteminkLab/TOP-paper-resources
[mit-license]: https://opensource.org/licenses/mit-license.html
[snakemake]: https://snakemake.readthedocs.io/en/stable/
[snakemake-pipeline]: https://github.com/HarteminkLab/TOP-paper-resources/tree/main/code/snakemake
[pretrained-model]: https://github.com/HarteminkLab/TOP-paper-resources/tree/main/data/trained_model_coef
[top-predictions]: https://duke.box.com/v/toppredictionsgr202204
